apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-and-push-pr-
spec:
  serviceAccountName: 'fsgroup-runasany'
  pipelineRef:
    name: build-and-push-pipeline
  workspaces:
  - name: myworkspace
    persistentVolumeClaim:
      claimName: tekton-pvc-jegan 
    subPath: source 
