apiVersion: v1
kind: Pod
metadata:
  name: pod-using-secrets
spec:
  restartPolicy: Never
  containers:
  - name: my-pod
    image: registry.k8s.io/busybox
    command: ["/bin/sh", "-c", "env"]
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: mysql-login-credentials
          key: username

    - name: PASSWORD 
      valueFrom:
        secretKeyRef:
          name: mysql-login-credentials
          key: password 
