apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: mysql
    name: jegan
spec:
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "192.168.1.108"
    path: "/mnt/mysql"
