apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc # Append your name like mysql-pvc-jegan
  labels:
    type: mysql
    name: jegan  #Replace this with your name
spec:
  selector:
    matchLabels:
      type: mysql
      name: jegan  #Replace this with your name
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
