apiVersion: batch/v1
kind: Job 
metadata:
  name: my-job
  labels:
    app: my-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name:  busybox 
        image: registry.k8s.io/busybox 
        command: ["/bin/sh", "-c", "env" ]
